version: '3.4'

services:
  banking.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  transfer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  identity.server:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

